# Generated by Django 2.0.6 on 2018-07-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180728_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Register'),
        ),
    ]
