# Generated by Django 2.0.6 on 2018-07-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180728_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
