# Generated by Django 2.0.6 on 2018-07-29 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0004_auto_20180729_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('addr', models.TextField(max_length=50)),
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.AddField(
            model_name='login',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Register'),
        ),
    ]
